version: '3.7'

services:
    paypage_sans_iframe:
        build: .
        container_name: victime_website_container
        restart: always
        volumes: 
            - ./public:/var/www/html
        ports: 
            - 8096:443   
        links: 
            - dropserver     

    dropserver:
        build: ./drop-server
        container_name: drop_server_container_iframe
        restart: always
        volumes: 
            - ./drop-server:/var/www/html
        ports: 
            - 8066:80 
        links:
            - fluentd
        logging:
            driver: "fluentd"
            options:
                fluentd-address: localhost:24224
                tag: httpdd.access

    fluentd:
        build: ./fluentd
        volumes:
            - ./fluentd/conf:/fluentd/etc
        links:
            - "elasticsearch"
        ports:
            - "24224:24224"
            - "24224:24224/udp"

    elasticsearch:
        build: ./elasticsearch
        container_name: elasticsearch_dropserver_ifr
        volumes:
            - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
        expose:
            - "9200"    
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            ES_JAVA_OPTS: "-Xmx256m -Xms256m"
   
    
    kibana:
        build: ./kibana
        container_name: kibana_dropserevr_ifr
        volumes:
            - ./kibana/config/:/usr/share/kibana/config:ro
        links: 
            - "elasticsearch"      
        ports:
            - 5601:5601
                 
                   
volumes: 
    public:
    drop-server:
       
